Development: 
  writer: 
    family: Mysql
    username: "root"
    driver: 'org.gjt.mm.mysql.Driver'
    password: "password"
    url: "jdbc:mysql://localhost:3306/appdb?characterEncoding=utf8"
    datasource: org.apache.commons.dbcp.BasicDataSource
    quote: "`keyword`"
    schema: appdb
    prefix: ~
    formats:
      datetime: 'yyyy-MM-dd HH:mm:ss.SSS'
      date: 'yyyy-MM-dd'
      time: 'HH:mm:ss.SSS'
  reader: 
    family: Mysql
    username: "root"
    driver: 'org.gjt.mm.mysql.Driver'
    password: "password"
    url: "jdbc:mysql://localhost:3306/appdb?characterEncoding=utf8"
    datasource: org.apache.commons.dbcp.BasicDataSource
    quote: "`keyword`"
    schema: appdb
    prefix: ~
    formats:
      datetime: 'yyyy-MM-dd HH:mm:ss.SSS'
      date: 'yyyy-MM-dd'
      time: 'HH:mm:ss.SSS'
     
Production:
  writer:  
    family: Mysql
    username: "root"
    driver: 'org.gjt.mm.mysql.Driver'
    password: "password"
    url: "jdbc:mysql://localhost:3306/core?characterEncoding=utf8"
    datasource: org.apache.commons.dbcp.BasicDataSource
    quote: "`keyword`"
    schema: "core"
    prefix: 'table_perfix'
    pluralized: true
    formats:
      datetime: 'yyyy-MM-dd HH:mm:ss.SSS'
      date: 'yyyy-MM-dd'
      time: 'HH:mm:ss.SSS'
  reader:  
    family: Mysql
    username: "root"
    driver: 'org.gjt.mm.mysql.Driver'
    password: "password"
    url: "jdbc:mysql://localhost:3306/core?characterEncoding=utf8"
    datasource: org.apache.commons.dbcp.BasicDataSource
    quote: "`keyword`"
    schema: "core"
    prefix: 'table_perfix'
    pluralized: true
    formats:
      datetime: 'yyyy-MM-dd HH:mm:ss.SSS'
      date: 'yyyy-MM-dd'
      time: 'HH:mm:ss.SSS'      
    